name: Setup Environment
description: Setup the environment for the build
inputs:
  dockerhub_token:
    description: The Docker Hub token
    required: true
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 8
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        cache: "pnpm"
    - shell: bash
      run: |
        pnpm install
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: akarachan
        password: ${{ inputs.dockerhub_token }}
